version: '3.8'

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
